import { API_CONFIG } from "./api-config.js";
import { CACHE_CONFIG } from "./cache-config.js";
import { UI_CONFIG } from "./ui-config.js";

// Master configuration object that merges API/cache/UI settings.
export const CONFIG = {
  // API endpoints
  API: {
    COINGECKO_BASE: API_CONFIG.COINGECKO_BASE,
    CRYPTOCOMPARE_BASE: API_CONFIG.CRYPTOCOMPARE_BASE,
    CHART_HISTORY_DAYS: API_CONFIG.CHART_HISTORY_DAYS,

  },

  // (API + Cache)
  NEWS: {
    BASE_URL: API_CONFIG.NEWS.BASE_URL,
    API_KEY: API_CONFIG.NEWS.API_KEY,
    DEFAULT_QUERY: UI_CONFIG.NEWS.DEFAULT_QUERY,
    LANGUAGE: UI_CONFIG.NEWS.LANGUAGE,
    CACHE_TTL_MS: CACHE_CONFIG.NEWS_CACHE.TTL_MS,
    FRESH_WINDOW_MS: CACHE_CONFIG.NEWS_CACHE.FRESH_WINDOW_MS,
    CACHE_KEYS: UI_CONFIG.NEWS.CACHE_KEYS,
  },

  // Cache settings
  CACHE: CACHE_CONFIG.CACHE,
  STORAGE_KEYS: CACHE_CONFIG.STORAGE_KEYS,

  // UI settings
  DISPLAY: UI_CONFIG.DISPLAY,
  REPORTS: UI_CONFIG.REPORTS,
  CHART: UI_CONFIG.CHART,
  UI: UI_CONFIG.UI,
  SEARCH: UI_CONFIG.SEARCH,
  NEWS_UI: UI_CONFIG.NEWS_UI,
  CURRENCIES: UI_CONFIG.CURRENCIES,
  ABOUT: UI_CONFIG.ABOUT,
};
