import { API_CONFIG } from "./api-config.js";
import { CACHE_CONFIG } from "./cache-config.js";
import { UI_CONFIG } from "./ui-config.js";
import { CONTENT_CONFIG } from "./content.js";

export const CONFIG = {
  API: {
    COINGECKO_BASE: API_CONFIG.COINGECKO_BASE,
    CRYPTOCOMPARE_BASE: API_CONFIG.CRYPTOCOMPARE_BASE,
  },
  NEWS: {
    BASE_URL: API_CONFIG.NEWS_API.BASE_URL,
    API_KEY: API_CONFIG.NEWS_API.API_KEY,
    DEFAULT_QUERY: CONTENT_CONFIG.NEWS.DEFAULT_QUERY,
    LANGUAGE: CONTENT_CONFIG.NEWS.LANGUAGE,
    CACHE_TTL_MS: CACHE_CONFIG.NEWS_CACHE.TTL_MS,
    FRESH_WINDOW_MS: CACHE_CONFIG.NEWS_CACHE.FRESH_WINDOW_MS,
    CACHE_KEYS: CONTENT_CONFIG.NEWS.CACHE_KEYS,
  },
  CACHE: CACHE_CONFIG.CACHE,
  STORAGE_KEYS: CACHE_CONFIG.STORAGE_KEYS,
  DISPLAY: UI_CONFIG.DISPLAY,
  REPORTS: UI_CONFIG.REPORTS,
  CHART: UI_CONFIG.CHART,
  UI: UI_CONFIG.UI,
  NEWS_UI: UI_CONFIG.NEWS_UI,
  CURRENCIES: UI_CONFIG.CURRENCIES,
  ABOUT: CONTENT_CONFIG.ABOUT,
};
